arg_int =
{
------------------------------------------------------------------------ ELECTRICAL_PANEL
	Battery_Relays_switch = 1000,
	external_power_APU_selector = 1001,
	AC_external_power_on_indicator_light = 1002,
	Engine1_Generator_switch = 1003,
	Engine2_Generator_switch = 1004,
	Engine3_Generator_switch = 1005,
	Engine4_Generator_switch = 1006,
	battery_test_selector = 1007,
------------------------------------------------------------------------ ENGINE_START_PANEL
	Engine1_Selector = 1009,
	Engine1_startlight = 1010,
	Engine2_Selector = 1012,
	Engine2_startlight = 1013,
	Engine3_Selector = 1015,
	Engine3_startlight = 1016,
	Engine4_Selector = 1018,
	Engine4_startlight = 1019,
------------------------------------------------------------------------ PROPELLER_CONTROL_PANEL
	Engine1PropControl_selector = 1020,
	Engine2PropControl_selector = 1021,
	Engine3PropControl_selector = 1022,
	Engine4PropControl_selector = 1023,
	FADEC1_Switch_Guard = 1024,
	FADEC1_Switch = 1025,
	FADEC2_Switch_Guard = 1026,
	FADEC2_Switch = 1027,
	FADEC3_Switch_Guard = 1028,
	FADEC3_Switch = 1029,
	FADEC4_Switch_Guard = 1030,
	FADEC4_Switch = 1031,
------------------------------------------------------------------------ THROTTLE_QUADRANT_ASSEMBLY
	Engine1SpeedMode_light = 1044,
	Engine2SpeedMode_light = 1045,
	Engine3SpeedMode_light = 1046,
	Engine4SpeedMode_light = 1047,
------------------------------------------------------------------------ APU_PANEL
	-- APU_Selector_Value = 1049,
	APU_Selector = 1050,
	APU_Selector_light = 1051,
	APU_alarm_switch = 1052,
	APU_intake_door = 1053,
--------------------------------------------------------------------------------- Trim_tabs
	Trim_Tab_Elevator = 1056,
	Trim_Tab_Aileron = 1057,
	Trim_Tab_Rudder = 1058,
------------------------------------------------------------------------ NetTakeControl
	PILOT_NetTakeControl = 1059,
	COPILOT_NetTakeControl = 1060,
------------------------------------------------------------------------ LANDING_GEAR_LIGHTS_PANEL
	gear_lever = 1061,
	landing_lights_indicator_left_light_green = 1062,
	landing_lights_indicator_left_light_orange = 1063,
	landing_lights_indicator_nose_light_green = 1064,
	landing_lights_indicator_nose_light_orange = 1065,
	landing_lights_indicator_right_light_green = 1066,
	landing_lights_indicator_right_light_orange = 1067,
	LeftLandingLight_OnOff_switch = 1068,
	RightLandingLight_OnOff_switch = 1069,
	LeftLandingLight_ExtHldRet_indicators = 1070,
	RightLandingLight_ExtHldRet_indicators = 1071,
	LeftLandingLight_ExtHldRet_switch = 1072,
	RightLandingLight_ExtHldRet_switch = 1073,
	LeftLandingLight_Spot_Illumination = 1074,
	RightLandingLight_Spot_Illumination = 1075,
	LeftLandingLight_Spot_Rotate = 1076,
	RightLandingLight_Spot_Rotate = 1077,
	Taxi_Lights_OnOff_switch = 1078,
	Taxi_Lights_Spot_Illumination = 1079,
	Wingtip_Taxi_Lights_OnOff_switch = 1080,
------------------------------------------------------------------------ HYDRAULIC_CONTROL_PANEL
	Cockpit_Aux_Hydraulic_Switch = 1080,
	anti_skid_switch = 1081,
	Emergency_Brake_Sel_Light = 1082,
	Engine_Pumps_Util_1_Light = 1083,
	Engine_Pumps_Util_2_Light = 1084,
	Engine_Pumps_Boost_3_Light = 1085,
	Engine_Pumps_Boost_4_Light = 1086,
	Suction_Boost_Pumps_Util_Light = 1087,
	Suction_Boost_Pumps_Boost_Light = 1088,
------------------------------------------------------------------------ Landing gear
	Gear_Nose = 1093,
	Gear_Left = 1094,
	Gear_Right = 1095,
	Gear_Nose_Supplement = 1096,
	Gear_Left_Supplement = 1097,
	Gear_Right_Supplement = 1098,
------------------------------------------------------------------------ WING_FLAPS_CONTROL_QUADRANT_PANEL
	flap_lever = 1100,
------------------------------------------------------------------------ PILOT_HUD_PANEL
	PILOT_hud_contrast_control = 1104,
	pilot_hud_brighness_control = 1105,
	pilot_hud_combiner_latch = 1106,
	pilot_hud_stopwatch = 1107,
------------------------------------------------------------------------ COPILOT_HUD_PANEL
	COPILOT_hud_contrast_control = 1114,
	copilot_hud_brighness_control = 1115,
	copilot_hud_combiner_latch = 1116,
	copilot_hud_stopwatch = 1117,
------------------------------------------------------------------------ DISPLAY_BRIGHTNESS_CONTROL
	hdd_001_brightness_control = 1125,
	hdd_002_brightness_control = 1126,
	hdd_003_brightness_control = 1127,
	hdd_004_brightness_control = 1128,
	pilot_CNI_MU_brightness_control = 1129,
	copilot_CNI_MU_brightness_control = 1130,
	CNBP_brightness_control = 1131,
	pilot_AMU_brightness_control = 1132,
	copilot_AMU_brightness_control = 1133,
	Observer_CNI_MU_brightness_control = 1134,
------------------------------------------------------------------------ REFERENCE_SET_MODE_SELECT_PANELS
	PILOT_reference_select_switch = 1140,
	PILOT_reference_set_knob = 1141,
	pilot_altimeter_setting_knob = 1142,
	pilot_baro_setting_knob = 1143,
	copilot_reference_select_switch = 1144,
	copilot_reference_set_knob = 1145,
	copilot_altimeter_setting_knob = 1146,
	copilot_baro_setting_knob = 1147,
	Alt_Hold_Light = 1148,
	Alt_Select_Light = 1149,
	Hdg_Light = 1150,
	Nav_Light = 1151,
	Approach_Light = 1152,
	Ver_Speed_Hold_Light = 1153,
	IAS_Light = 1154,
	CAPS_Light = 1155,
	Autothrottle_Light = 1156,
------------------------------------------------------------------------ FUEL_MANAGEMENT_PANEL
	Left_Dump_Switch_Guard = 1160,
	Left_Dump_Switch = 1161,
	Right_Dump_Switch_Guard = 1162,
	Right_Dump_Switch = 1163,
	Left_External_Transfer_Switch = 1164,
	One_Main_Transfer_Switch = 1165,
	Two_Main_Transfer_Switch = 1166,
	Left_Aux_Transfer_Switch = 1167,
	Right_Aux_Transfer_Switch = 1168,
	Three_Main_Transfer_Switch = 1169,
	Four_Main_Transfer_Switch = 1170,
	Right_External_Transfer_Switch = 1171,
	Fuel_Tank_Select = 1172,
	Fuel_QTY_Set = 1173,
	SPR_Valve_Switch = 1174,
	X_Ship_Switch = 1175,
	X_Feed_Eng1_Switch = 1176,
	X_Feed_Eng2_Switch = 1177,
	X_Feed_Eng3_Switch = 1178,
	X_Feed_Eng4_Switch = 1179,
------------------------------------------------------------------------ THROTTLES
	throttleInput1 = 1187,
	throttleInput2 = 1188,
	throttleInput3 = 1189,
	throttleInput4 = 1190,
------------------------------------------------------------------------ MISCELLANEOUS
	Debug_Screen = 1199,
	Rocket_Assist_Arm_Switch_Guard = 1200,
	Rocket_Assist_Arm_Switch = 1201,
	Rocket_Assist_Fire_Trigger_Button = 1202,
	Park_Brake_Mouse = 1203,
	CargoFWD_CrewLoad_Anim = 1204,
	CargoMID_CrewLoad_Anim = 1205,
	CargoAFT_CrewLoad_Anim = 1206,
	Network_Sync = 1207,
	Rocket_Assist_Fire_Trigger_Light_Green = 1208,
	Rocket_Assist_Body = 1209,
	Rocket_Assist_Fire_Trigger_Light_Red = 1210,
	Missile_Pylon_Visibility = 1211,
	Cannon_Base_Visibility = 1212,
	-- PILOT_Headset = 1213,
	-- CargoRamp38Anim_Extension = 1214,
	CargoDoor = 1215,
	CargoRamp = 1216,
	Crew_Entrance_Door = 1217,
	CargoRampExtension = 1218,
	CargoSeatsRemove = 1219,
	Paratroop_Port_Door = 1220,
	Paratroop_Starboard_Door = 1221,
	CargoSeatsRemoveBattleStation = 1222,
	Pilot_Show_Cockpit = 1223,
	Copilot_Show_Cockpit = 1224,
	Pilot_Show_Cargo = 1225,
	Copilot_Show_Cargo = 1226,
	Flightdeck_Pilot_Window_Handle = 1227,
	Flightdeck_Copilot_Window_Handle = 1228,
	Pilot_Tacview_Attach_Lever = 1229,
	Hide_External_Geometry_From_Sensors = 1230,
	External_Lights_Hide_From_Cockpit = 1231,
	Pylon1234_bodies = 1232,
	-- Pylon1_Body = 1233,
	-- Pylon2_Body = 1234,
	-- Pylon3_Body = 1235,
	-- Pylon3_Body = 1236,
	Paratrooper_About_Turn = 1237,
	Herc_Paratrooper_Release_Count_FWD = 1238,
	Paratrooper_Jumping = 1239,
	Paratrooper_Squad_Visibility = 1240,
	Tow_Parachute_Deploy = 1241,
	Tow_Parachute_Pull = 1242,
------------------------------------------------------------------------ Aerial_Delivery_Panel
	Air_Deflector_Extend = 1278,--external
	Air_Deflector_Switch = 1279,
	Cockpit_Cargo_DoorRamp_Switch = 1280,
	Cockpit_Cargo_DoorRamp_Switch_Light = 1281,
	CargoFWD_AirDrop_Anim = 1282,
	CargoMID_AirDrop_Anim = 1283,
	CargoAFT_AirDrop_Anim = 1284,
	CargoFWDjettisonParatroopOffset = 1285,
	Computer_Drop_Switch = 1288,
	Bell_Alarm_Switch_Guard = 1289,
	Bell_Alarm_Switch = 1290,
	Chute_Release_Guard = 1291,
	Chute_Release_Trigger = 1292,
	CargoFWD_OffLoad = 1293,--external
	CargoMID_OffLoad = 1294,--external
	CargoAFT_OffLoad = 1295,--external
	Jump_Switch_Light = 1296,
	Caution_Switch_Light = 1297,
------------------------------------------------------------------------ ADI
	ADI_Knob = 1300,
	ADI_Pitch = 1301,
	ADI_Bank = 1302,
	ADI_Slipball = 1303,
	ADI_TurnNeedle = 1304,
------------------------------------------------------------------------ NOSE_WHEEL_STEERING
	Nose_wheel_steering = 1305,
------------------------------------------------------------------------ FLAP_TRIM_INDICATOR_PANEL
	FlapIndicator = 1306,
	AileronTrimIndicator = 1307,
	RudderTrimIndicator = 1308,
	ElevatorTrimIndicator = 1309,
------------------------------------------------------------------------ MAGNETIC_COMPASS
	MagneticCompass_Rot = 1310,
	MagneticCompass_Pitch = 1311,
	MagneticCompass_Bank = 1312,
------------------------------------------------------------------------ FLIGHT_CONTROL_WHEELS
	FLIGHT_CONTROL_Pitch = 1313,
	FLIGHT_CONTROL_Bank = 1314,
------------------------------------------------------------------------ CLOCK
	Clock_Hour = 1315,
	Clock_Minute = 1316,
	Clock_Second = 1317,
------------------------------------------------------------------------ Battle_Station
	Cannon_Reticules_show = 1328,
	Pylon_Bomb_Fuse_Switch = 1329,
	Pylon_Bomb_Fuse_Switch_Light = 1330,
	Pylon_Control_Reset_Switch = 1331,
	Cannon_Stabilizer_Switch = 1332,
	Cannon_Stabilizer_Light = 1333,
	Pylon1_Control_Switch = 1334,
	Pylon1_Control_Switch_Light_Green = 1335,
	Pylon1_Control_Switch_Light_Red = 1336,
	Pylon2_Control_Switch = 1337,
	Pylon2_Control_Switch_Light_Green = 1338,
	Pylon2_Control_Switch_Light_Red = 1339,
	Pylon3_Control_Switch = 1343,
	Pylon3_Control_Switch_Light_Green = 1344,
	Pylon3_Control_Switch_Light_Red = 1345,
	Pylon4_Control_Switch = 1346,
	Pylon4_Control_Switch_Light_Green = 1347,
	Pylon4_Control_Switch_Light_Red = 1348,
	Pylon_Release_Button = 1355,
	Cannon_Release_Button = 1356,
	Cannon_Station_Select_Knob = 1357,
	Master_Arm_Switch_Guard = 1358,
	Master_Arm_Switch = 1359,
	Battle_Station_Visibility = 1360,
	Battle_Station_Power_light = 1361,
	Battle_Station_Power = 1362,
	Cannon_Slave_TPOD = 1363,
	Cannon_Slave_TPOD_light = 1364,
	FLIR_DMT_Power_switch = 1365,
	FLIR_DMT_Power_switch_State = 1366,
	TPOD_Direction_select_switch = 1367,
	Pylons_Jettison_Switch_Guard = 1368,
	Pylons_Jettison_Switch = 1369,
------------------------------------------------------------------------ BLEED_AIR_PANEL
	Bleed_Air_Switch_Engine1 = 1370,
	Bleed_Air_Switch_Engine2 = 1371,
	Bleed_Air_Switch_Engine3 = 1372,
	Bleed_Air_Switch_Engine4 = 1373,
	Bleed_Air_Switch_RisoValve = 1374,
	Bleed_Air_Switch_DivValve = 1375,
	Bleed_Air_Switch_LisoValve = 1376,
	Bleed_Air_Switch_APU_Light = 1377,
------------------------------------------------------------------------ FIRE_HANDLES
	Engine1_fire_handle = 1380,
	Engine1_fire_handle_light = 1381,
	Engine2_fire_handle = 1382,
	Engine2_fire_handle_light = 1383,
	Engine3_fire_handle = 1384,
	Engine3_fire_handle_light = 1385,
	Engine4_fire_handle = 1386,
	Engine4_fire_handle_light = 1387,
	APU_fire_handle = 1388,
	APU_fire_handle_light = 1389,
------------------------------------------------------------------------ Automatic_Flight_Control_System_Panel
	AFCS_Pilot_Engage_Lever = 1400,
	AFCS_Copilot_Engage_Lever = 1401,
	AFCS_Pitch_Switch_Light = 1402,
	AFCS_Lateral_Switch_Light = 1403,
	AFCS_Turn_Control = 1404,
	AFCS_Pitch_Control = 1405,
------------------------------------------------------------------------ Heading_Course_Selector_Control_Panel
	PILOT_HDG_Selector_Control = 1410,
	PILOT_CRS_Selector_Control = 1411,
	COPILOT_HDG_Selector_Control = 1412,
	COPILOT_CRS_Selector_Control = 1413,
------------------------------------------------------------------------ICS_PANEL (Intercommunications System)
	PILOT_ICS_Volume_Rot = 1430,
	PILOT_ICS_Volume_Pull = 1431,
	COPILOT_ICS_Volume_Rot = 1432,
	COPILOT_ICS_Volume_Pull = 1433,
	PILOT_ICS_Undefined_Rot = 1434,
	COPILOT_ICS_Undefined_Rot = 1435,
------------------------------------------------------------------------ Annunciator_Panel
	AP_ON_Light = 1500,
	AP_DSNG_Light = 1501,
------------------------------------------------------------------------ RAMP_CONTROL_PANEL
	Aft_Aux_Hydraulic_Switch = 1550,
	Aft_Cargo_Door_Switch = 1551,
	Aft_Cargo_Ramp_Switch = 1552,
------------------------------------------------------------------------ RAMP_EMERGENCY_CONTROL_PANEL
	Loadmaster_Cargo_DoorRamp_Switch = 1560,
	Cargo_Jett_Locks_FWD_Switch_Guard = 1561,
	Cargo_Jett_Locks_FWD_Switch = 1562,
	Cargo_Jett_Locks_MID_Switch_Guard = 1563,
	Cargo_Jett_Locks_MID_Switch = 1564,
	Cargo_Jett_Locks_AFT_Switch_Guard = 1565,
	Cargo_Jett_Locks_AFT_Switch = 1566,
	-- Locks_Switch_Guard = 1567,
	-- Locks_Switch = 1568,
	-- Airdrop_Airdrop_Hold_Switch = 1569,
	Airdrop_Drogue_Switch_Guard = 1570,
	Airdrop_Drogue_Switch = 1571,
	-- Airdrop_Towplate_Switch_Guard = 1572,
	-- Airdrop_Towplate_Switch = 1573,
----------------------------------------------------------------------------------LOADMASTER_STATION
	LMPanel_Power = 1580,
	LMPanel_Screen_brightness = 1581,
----------------------------------------------------------------------------------PILOT_LIGHTNING_CONTROLS
	Cockpit_Dome_Brighness_Control = 1600,
	Cockpit_Dome_Intensity = 1601,
	Master_Switch_Control = 1602,
	Pilot_Display_Master_Brighness_Control = 1603,
----------------------------------------------------------------------------------COPILOT_LIGHTNING_CONTROLS
	Overhead_Panel_Flood_Intensity = 1611,
	Overhead_Panel_Flood_Brighness_Control = 1612,
	Copilot_Display_Master_Brighness_Control = 1613,
----------------------------------------------------------------------------------FWD_CARGO_LIGHTING_CONTROL_PANEL
	Fwd_Cargo_Lighting_Dome_Brightness_Control = 1620,
	Fwd_Cargo_Lighting_Dome_Intensity = 1621,
	Fwd_Cargo_Lighting_Master_Control = 1622,
	Fwd_Cargo_Lighting_Ramp_Door_Insp_Lt_Control = 1623,
	Fwd_Cargo_Lighting_Panel_Control = 1624,
	Fwd_Cargo_Lighting_Panel_Intensity = 1625,
----------------------------------------------------------------------------------AFT_CARGO_LIGHTING_CONTROL_PANEL
	Aft_Cargo_Lighting_Dome_Brightness_Control = 1630,
	Aft_Cargo_Lighting_Dome_Intensity = 1631,
	Aft_Cargo_Lighting_Jump_Platform_Control = 1632,
	Aft_Cargo_Lighting_Jump_Platform_Intensity = 1634,
	Aft_Cargo_Lighting_Jump_Light_Control = 1635,
	Aft_Cargo_Lighting_Panel_Control = 1636,
	Aft_Cargo_Lighting_Ramp_Dome_Brightness_Control = 1637,
	Aft_Cargo_Lighting_Ramp_Dome_Intensity = 1638,
	Aft_Cargo_Lighting_Ramp_Door_Insp_Lt_Control = 1640,
	Aft_Cargo_Lighting_Panel_Intensity = 1641,
	Aft_Cargo_Ramp_Loading_Light_Switch = 1642,
	Aft_Cargo_Ramp_Loading_Light_Intensity = 1643,
----------------------------------------------------------------------------------AUGMENTED_CREW_LIGHTING_CONTROLS
	Augmented_Crew_Lighting_Flood_Control = 1650,
	Augmented_Crew_Lighting_Flood_Intensity = 1651,
----------------------------------------------------------------------------Cannons Slew
	Cannon_Howitzer_Body = 1697,
	Cannon_Chain_Gun_Body = 1698,
	Cannon_Vulcan_Body = 1699,
	Cannon_Howitzer_Azimuth = 1700,
	Cannon_Howitzer_Elevation = 1701,
	Cannon_Howitzer_Roll_Stabilize = 1702,
	Cannon_Howitzer_Pitch_Stabilize = 1703,
	Cannon_Howitzer_Yaw_Stabilize = 1704,
	Cannon_Howitzer_Reticule_Azimuth = 1705,
	Cannon_Howitzer_Reticule_Elevation = 1706,
	Cannon_Chain_Gun_Azimuth = 1707,
	Cannon_Chain_Gun_Elevation = 1708,
	Cannon_Chain_Gun_Roll_Stabilize = 1709,
	Cannon_Chain_Gun_Pitch_Stabilize = 1710,
	Cannon_Chain_Gun_Yaw_Stabilize = 1711,
	Cannon_Chain_Gun_Reticule_Azimuth = 1712,
	Cannon_Chain_Gun_Reticule_Elevation = 1713,
	Cannon_Vulcan_Azimuth = 1714,
	Cannon_Vulcan_Elevation = 1715,
	Cannon_Vulcan_Roll_Stabilize = 1716,
	Cannon_Vulcan_Pitch_Stabilize = 1717,
	Cannon_Vulcan_Yaw_Stabilize = 1718,
	Cannon_Vulcan_Reticule_Azimuth = 1719,
	Cannon_Vulcan_Reticule_Elevation = 1720,
----------------------------------------------------------------------------------Props animation
	Feather_Prop_001 = 1800,
	Feather_Prop_002 = 1801,
	Feather_Prop_003 = 1802,
	Feather_Prop_004 = 1803,
	Engine1NP = 1804,
	Engine2NP = 1805,
	Engine3NP = 1806,
	Engine4NP = 1807,
	Hub_Rotation_Prop_001 = 1808,
	Hub_Rotation_Prop_002 = 1809,
	Hub_Rotation_Prop_003 = 1810,
	Hub_Rotation_Prop_004 = 1811,
	Continous_Rotation_Prop = 1812,
	Hub_Visibility_Prop_001 = 1813,
	Hub_Visibility_Prop_002 = 1814,
	Hub_Visibility_Prop_003 = 1815,
	Hub_Visibility_Prop_004 = 1816,
----------------------------------------------------------------------- 
----------------------------------------------------------------------- 
}

















